# docker-compose.yml
version: "3.8"
services:
  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: mongo
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: password
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    ports:
      - '27017:27017'
    volumes:
      - './tmp/database/mongo-db:/bitnami/mongodb'
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: password
#      #- ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
#      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin
#    depends_on:
#      - mongo
#    restart: unless-stopped   
#    ports:
#      - "8081:8081"